# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170916_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(max_length=10),
        ),
    ]
