# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 17:44
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170916_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='user.Book'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
